### PR TITLE
Strip the SIP port in dns queries 

### PR DESCRIPTION
**Pull request by pierok13**

### CODE REVIEW

**Comment by lmangani** [comment]
Curious as if they do not work because a custom DNS is required or in general?

**Comment by lmangani** [comment]
May I suggest adding a parameter for dns, false by default, and until false bypass the dns lookup entirely?

**Comment by pierok13** [comment]
You may be right, let me check why it's failing
ok, I will just strip the port from the source IP, then dns should work.
let me submit another PR

**Comment by pierok13** [comment]
I couldn't test it but this should work

**Pull request merged**
