### PR TITLE
Added Cisco VG and Audiocodes SBC app

### PR DESCRIPTION
**Pull request by pierok13**
I'm using that since a month, looks like to work with some errors, but it helped me troubleshoot some issues.
I don't pretend that this is working 100% but maybe the community can leverage that work to make it even better !

### CODE REVIEW

**Comment by pierok13** [comment]
I didn't see that in between @os11k  worked also on an audiocodes app ! I feel little when I see what you did.... :(

**Comment by lmangani** [comment]
Thanks for your contribution @pierok13! 

Would you be able submit those as plugin modules instead? It only requires minor changes and will be pushed as @pastash/pastash modules on npm for simple recipe building. You can find other examples [here](https://github.com/sipcapture/paStash/tree/next/plugins) including our version of the Audiocodes parser - perhaps you could merge your changes there, and create a new plugin for the Cisco one? Many eyes are better than a few, so it's all great!

If you do not have time/space, just let us know and we'll do the porting. Once again thanks for sharing!

**Comment by os11k** [comment]
Hi @pierok13 ! Do you plan to merge any code to audiocodes_filter? I would like to make more improvements, but maybe you already did some. I just want to avoid double work.

**Comment by pierok13** [comment]
Go ahead I don't have much time to work on it on a frequent basis....
-------- Message d'origine --------De : Jurijs I <notifications@github.com> Date : 04/02/2021  19:40  (GMT+01:00) À : sipcapture/paStash <paStash@noreply.github.com> Cc : pierok13 <pierok@yahoo.fr>, Mention <mention@noreply.github.com> Objet : Re: [sipcapture/paStash] Added Cisco VG and Audiocodes SBC app (#83) 
Hi @pierok13 ! Do you plan to merge any code to audiocodes_filter? I would like to make more improvements, but maybe you already did some. I just want to avoid double work.

**Comment by lmangani** [comment]
@pierok13 I'll take care of it, but could you at least show an example usage for the Cisco plugin? I have no idea what input it takes and how to document it otherwise :)

**Comment by lmangani** [comment]
Feel free to PR to the [plugin readme](https://github.com/sipcapture/paStash/blob/next/plugins/filters/app_cisco/app_cisco.md)

**Comment by lmangani** [comment]
Thanks again @pierok13 for your contribution! Module published

+ @pastash/filter_app_cisco@1.0.1

**Pull request closed without merging**
