### PR TITLE
Janus OTLP Tracer & Prometheus Exporter

### PR DESCRIPTION
**Pull request by lmangani**

### CODE REVIEW

**Comment by lmangani** [comment]
Note: in theory the non-library version is no longer needed as the new version could be instrumented to serve both UPTRACE and cLoki/zipkin at once

**Comment by Dletta** [comment]
I will finish adding 'all' events. Then we need to test the above hypothesis for zipkin. After which we can merge it, :)

**Comment by lmangani** [comment]
Ready to merge?

**Comment by Dletta** [comment]
Changes in janus-uptrace overrule this branch and PR

**Pull request closed without merging**
