### PR TITLE
Updated audiocodes plugin so it supports Audiocodes 7.20A.256.511 

### PR DESCRIPTION
**Pull request by os11k**
Updated this pull request based on @lmangani recommendations

### CODE REVIEW

**Review by lmangani — APPROVED** [review]

**Comment by lmangani** [comment]
Wonderful! So this tests successfully in your setup right?

Note to self: update `readme` with the new setting, increase the `version` in package.json to release the new version.

**Comment by os11k** [comment]
Hi @lmangani ! It works in most cases, but sometimes some packets slips through(487 for example) and I can't wrap my head around why. Sometimes I can see it with my debug line `if (this.debug) console.info('DEBUG', line);` and not with `reassembled line`, but sometimes I can see it with `reassembled line` and it even matches regex, but still sends nothing to Homer. But in most cases it works. Anyway it works fine and I see traffic in my Homer and in most cases I do not need all of the packets to figure out where problem with traffic was. I will run this with 4 more different Audiocodes, maybe then I will get more ideas what to improve. Thank you!

**Comment by lmangani** [comment]
@os11k if you can replicate the missing packet data for me I'd be happy to take a look - let's go for 100% :)
I suspect the issue will be in terms of how the messages are split across messages....

**Comment by lmangani** [comment]
@os11k thinking out loud.... if the log apparently matches the regex but fails, its probably multi-line. JS regex hates it.

**Comment by os11k** [comment]
How I can send you logs privately, due security concers? I have now case where ACK were not sent to Homer

**Comment by lmangani** [comment]
@os11k you can send logs to support at sipcapture . org (please refer this issue in the title)

**Comment by os11k** [comment]
Sent, check line 1010. I see ACK, but nothing is sent towards Homer.

**Comment by lmangani** [comment]
There seems to be no marker for this ACK packet so we can't tell if its in/out or where its from/to. Potentially a lost event?
You are using TCP syslog right?

missing event:
```
---- Outgoing SIP Message ...
```

**Comment by os11k** [comment]
Audiocodes sends Syslogt events to UDP port, this is what you asked. Correct?

**Comment by lmangani** [comment]
@os11k change to TCP in both SBC and Pastash, its probably packet loss.
```
input {
  tcp {
    host => 0.0.0.0
    port => 514
    type => syslog
  }
}
```

**Comment by os11k** [comment]
Seems Audiocodes is not supporting Syslog via TCP. :(

**Comment by lmangani** [comment]
@os11k ouch.... :( that's really bad

**Comment by lmangani** [comment]
Well let's see if that's a theory - do you see ANY other ACK message successfully delivered?

**Comment by os11k** [comment]
Yes, I see ACKs for other calls. Now for example I made a call and invite got lost, but everything else is there. Now I'm trying to find a case when I see packet with `reassembled line` and regex correct, but still no packet, but no luck yet.

**Comment by lmangani** [comment]
Considering we have to deal with UDP loss, paStash must be deployed be in near proximity if not local to the same switch to succeed.

**Comment by lmangani** [comment]
Since the issue seems to be resolved and gaps are network related, I think we should merge this and proceed on top - would you agree?

**Comment by os11k** [comment]
Yes, I totally agree with you. Thank you!

**Pull request merged**
