### PR TITLE
add add_timestamp_field filter

### PR DESCRIPTION
**Pull request by grumvalski**

### CODE REVIEW

**Comment by lmangani** [comment]
@grumvalski dupe of [compute_date_field](https://github.com/sipcapture/paStash/blob/master/docs/filters/compute_date_field.md) ?

**Comment by grumvalski** [comment]
Nope, compute_date_field formats the field as a timestamp but sends it as
string (between "") and not as an unquoted integer.

**Comment by lmangani** [comment]
@grumvalski I would propose extending the existing method with an option to push out an integer from Moment?

**Comment by grumvalski** [comment]
Not sure it is possible with moment not to include the quotes in its output
fields.

**Pull request closed without merging**
