### PR TITLE
Updated audiocodes plugin so it supports Audiocodes 7.20A.256.511

### PR DESCRIPTION
**Pull request by os11k**
Not the prettiest code I wrote, but it works for me. If we will get more and more different regexs, then maybe I will update it. Additionally I added One line what print outs everything paStash receives what I believe is very useful for debug.

### CODE REVIEW

**Comment by lmangani** [comment]
Thanks for the PR! from the changes its slightly unclear as of how this would be backwards compatible between regex and regex_1? or should we assume this being compatible with the older versions? 

BTW pastash has `stdout` functions already which offer a debug view into data at each stage, if useful.

**Comment by os11k** [comment]
@lmangani 

Do you mean like this:

```
input {
  udp {
    host => 0.0.0.0
    port => 10514
    type => syslog
  }
}

filter {
  app_audiocodes {
    debug => true
    autolocal => true
    qos => true
    localip => 10.43.56.13
  }
}

output {
stdout{}
  if [rcinfo] != 'undefined' {
        hep {
          host => '10.182.151.163'
          port => 9060
          hep_id => 100
          hep_type => 1
        }
  }
}
```
Can I print everything out? By using `stdout{}` line? In this case we do print only what app_audiocodes is able to parse. Or there is other way to print out completely everything? Sorry for stupid question. :(


```
var regex = /(.*)---- Incoming SIP Message from (.*) to SIPInterface #[0-99] \((.*)\) (.*) TO.*--- #012(.*)#012 #012(.*)/g; //7.20A.260.012
var regex_1 = /(.*)---- Incoming SIP Message from (.*) to SIPInterface #[0-99] \((.*)\) (.*) TO.*---  (.*)(.*)/g; //7.20A.256.511
var ip = regex.exec(line);
if (!ip){
       ip = regex_1.exec(line);
}
```

In first 2 lines we set regex & regex_1 with different regular expressions. Then `ip = regex.exec(line);` is setting `ip` variable. If first regular expression do not work `ip` should be NULL, that we check with if and if it is NULL we check second regular expression(regex_1). After this IP should be NULL if none of this 2 regular expressions works and it should be not NULL if any of it works. I suppose it should work like this. No? I really not a good in js, but for me it seems right, no?

**Comment by lmangani** [comment]
The fallback approach surely might work but we'd be potentially wasting lots of cycles and incrementally decrease performance if/when new version changes are required. My proposal here would be having multiple regex filters per "version" one could select from the plugin settings. This way it would be easier to understand where failures happen.

Pseudo-code. We could set an optional parameter with a default:
```
optional_params: [ ... 'version'],
default_values: {
   ...
   version: '7.20A.260.012'
]
```
and then use it in the parser:
```
      var regex;
      if (this.version == '7.20A.260.012') {
           regex = /(.*)---- Incoming SIP Message from (.*) to SIPInterface #[0-99] \((.*)\) (.*) TO.*--- #012(.*)#012 #012(.*)/g; //7.20A.260.012
      } else if (this.version == '7.20A.256.511'){
	   regex = /(.*)---- Incoming SIP Message from (.*) to SIPInterface #[0-99] \((.*)\) (.*) TO.*---  (.*)(.*)/g; //7.20A.256.511
      }
      var ip = regex.exec(line);
```

**Review by lmangani — CHANGES_REQUESTED** [review]
The fallback approach surely might work but we'd be potentially wasting lots of cycles and incrementally decrease performance if/when new version changes are required. My proposal here would be having multiple regex filters per "version" one could select from the plugin settings. This way it would be easier to understand where failures happen.

Pseudo-code. We could set an optional parameter with a default:
```
optional_params: [ ... 'version'],
default_values: {
   ...
   version: '7.20A.260.012'
]
```
and then use it in the parser:
```
      var regex;
      if (this.version == '7.20A.260.012') {
           regex = /(.*)---- Incoming SIP Message from (.*) to SIPInterface #[0-99] \((.*)\) (.*) TO.*--- #012(.*)#012 #012(.*)/g; //7.20A.260.012
      } else if (this.version == '7.20A.256.511'){
	   regex = /(.*)---- Incoming SIP Message from (.*) to SIPInterface #[0-99] \((.*)\) (.*) TO.*---  (.*)(.*)/g; //7.20A.256.511
      }
      var ip = regex.exec(line);
```
This would be used simply by selecting a version:
```
filter {
  app_audiocodes {
    debug => true
    autolocal => true
    qos => true
    localip => 10.43.56.13
    version => 7.20A.256.511
  }
}
```

Perhaps it would be enough to get 260 and 256 but that's totally up to you guys - no clue how many versions there might be :)

**Comment by os11k** [comment]
Totally agree with you @lmangani . I will update pull request right now. Could you please explain me how I can print out messages what `filter_app_audiocodes` is not able to parse at all, it looks like that `if (this.debug) console.info('DEBUG', line);` do not works as I hoped. I would like to leave paStash running in my environment and check logs if any SIP messages were not parsed successfully I would like to see exactly full message what paStash receives. Thank you!

**Comment by os11k** [comment]
I will close this pull request and I will create new one as @lmangani you requested.

**Pull request closed without merging**
